//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solti.Utils.Router.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Solti.Utils.Router.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The route may not contain base URL..
        /// </summary>
        internal static string BASE_URL_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("BASE_URL_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converter cannot be found: &quot;{0}&quot;.
        /// </summary>
        internal static string CONVERTER_NOT_FOUND {
            get {
                return ResourceManager.GetString("CONVERTER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate parameter name found: &quot;{0}&quot;.
        /// </summary>
        internal static string DUPLICATE_PARAMETER {
            get {
                return ResourceManager.GetString("DUPLICATE_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chunk is empty..
        /// </summary>
        internal static string EMPTY_CHUNK {
            get {
                return ResourceManager.GetString("EMPTY_CHUNK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method cannot be empty..
        /// </summary>
        internal static string EMPTY_METHOD {
            get {
                return ResourceManager.GetString("EMPTY_METHOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inappropriate parameters..
        /// </summary>
        internal static string INAPPROPRIATE_PARAMETERS {
            get {
                return ResourceManager.GetString("INAPPROPRIATE_PARAMETERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format style: &quot;{0}&quot;.
        /// </summary>
        internal static string INVALID_FORMAT_STYLE {
            get {
                return ResourceManager.GetString("INVALID_FORMAT_STYLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid handler..
        /// </summary>
        internal static string INVALID_HANDLER {
            get {
                return ResourceManager.GetString("INVALID_HANDLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid HEX value.
        /// </summary>
        internal static string INVALID_HEX {
            get {
                return ResourceManager.GetString("INVALID_HEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given path is not valid: &quot;{0}&quot;.
        /// </summary>
        internal static string INVALID_PATH {
            get {
                return ResourceManager.GetString("INVALID_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid template..
        /// </summary>
        internal static string INVALID_TEMPLATE {
            get {
                return ResourceManager.GetString("INVALID_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route already registered:&quot; {0}&quot;.
        /// </summary>
        internal static string ROUTE_ALREADY_REGISTERED {
            get {
                return ResourceManager.GetString("ROUTE_ALREADY_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The route is not registered..
        /// </summary>
        internal static string ROUTE_NOT_REGISTERED {
            get {
                return ResourceManager.GetString("ROUTE_NOT_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A segment may contain one parameter descriptor only..
        /// </summary>
        internal static string TOO_MANY_PARAM_DESCRIPTOR {
            get {
                return ResourceManager.GetString("TOO_MANY_PARAM_DESCRIPTOR", resourceCulture);
            }
        }
    }
}
